package matrix:multiplication;


world matrix {
    record wasm-event {
        event: string
    }

    record wasm-result {
        output: string
    }
    export run: func(input: wasm-event) -> wasm-result;
}



