[package]
name = "matrix-multiplication-component"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen = "0.43.0"
serde_json = "1.0.142"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "docs:multiplication"

[build]
target = "wasm32-wasip2"  

